name: Bug report
description: Create a report to help us improve
labels:
  - bug
assignees:
  - nomorenotes/bugfixers
body:
  - type: textarea
    id: description
    label: "Describe the bug"
    description: "A clear and concise description of what the bug is."
    validations:
      required: true
  - type: textarea
    id: reproduction
    label: "To Reproduce"
    value: |
      1. Go to '...'
      2. Click on '....'
      3. Scroll down to '....'
      4. See error
    validations:
      required: true
  - type: textarea
    id: exprected
    label: "Expected behavior"
    description: "A clear and concise description of what you expected to happen."
    validations:
      required: true
  - type: textarea
    id: context
    label: "Additional context (optional)"
    description: "Add any other context about the problem here."