name: Install
on:
  push:
  pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Tell checkout what to checkout
      run: git config --global init.defaultBranch $GITHUB_REF
    - uses: actions/checkout@master
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Install
      run: |
        npm install
        git add package-lock.json
    - name: Push Lockfile
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
